- name: Disable ufw
  package:
      name: ufw
      state: absent

- name: Install firewalld
  package:
      name: firewalld
      state: present

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Make sure services are enabled
  firewalld:
    service: '{{ item }}'
    permanent: true
    state: enabled
    immediate: true
  with_items: '{{ firewalld_enabled_services }}'

- name: Make sure services are disabled
  firewalld:
    service: '{{ item }}'
    permanent: true
    state: disabled
    immediate: true
  with_items: '{{ firewalld_disabled_services }}'

- name: Make sure ports are enabled
  firewalld:
    port: '{{ item }}'
    permanent: true
    state: enabled
    immediate: true
  with_items: '{{ firewalld_enabled_ports }}'

- name: Make sure ports are disabled
  firewalld:
    port: '{{ item }}'
    permanent: true
    state: disabled
    immediate: true
  with_items: '{{ firewalld_disabled_ports }}'
